/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.PatientRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.PatientOrganisation;
import Business.Patient.Patient;
import Business.UserAccount.UserAccount;
import javax.swing.JPanel;
import java.awt.CardLayout;
import java.awt.Component;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import org.jdesktop.swingx.JXDatePicker;

/**
 *
 * @author prabhpreetsingh
 */
public class UpdatePatientInfo extends javax.swing.JPanel {

    /**
     * Creates new form UpdatePatientInfo
     */
    
    private JPanel containerJPanel;
    private EcoSystem ecosystem;
    private PatientOrganisation org;
    private UserAccount userAccount;
    private Enterprise enterprise;
    
    public UpdatePatientInfo(JPanel containerJPanel, UserAccount userAccount, Enterprise enterprise, EcoSystem ecosystem, PatientOrganisation org) {
        initComponents();
        this.ecosystem = ecosystem;
        this.containerJPanel = containerJPanel;
        this.userAccount = userAccount;
        this.enterprise = enterprise;
        this.org = org;
        
        populatePatientDetails();

       }
        
        
        
    
    
    public void populatePatientDetails(){

       
       for (Patient patient: org.getPatientDirectory().getPatientDirectory()){
           if(userAccount.getEmployee().getName().equalsIgnoreCase(patient.getName())){
               nameTextField.setText(patient.getName());
               dobField.setDate(patient.getDateOfBirth());
               contactTextField.setText(patient.getContactNo());
               addressTextField.setText(patient.getAddress());
               genderComboBox.setSelectedItem(patient.getGender());
               emailTextField.setText(patient.getEmail());
           }
           
       }
       
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        addressTextField = new javax.swing.JTextField();
        contactTextField = new javax.swing.JTextField();
        emailTextField = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();
        registerJButton = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        dobField = new org.jdesktop.swingx.JXDatePicker();
        genderComboBox = new javax.swing.JComboBox();

        jLabel1.setText("Patient Registration");

        jLabel2.setText("Name");

        jLabel3.setText("Date of Birth");

        jLabel4.setText("Gender");

        jLabel5.setText("Address");

        jLabel6.setText("Contact Number");

        jLabel7.setText("E-mail");

        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        registerJButton.setText("Update");
        registerJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerJButtonActionPerformed(evt);
            }
        });

        dobField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dobFieldActionPerformed(evt);
            }
        });

        genderComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "Male", "Female" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(869, 869, 869))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(593, 593, 593)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(backJButton)
                            .addGap(63, 63, 63)
                            .addComponent(registerJButton)
                            .addContainerGap()))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(genderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(307, 307, 307))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(addressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(contactTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dobField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, 0))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {addressTextField, contactTextField, emailTextField, jLabel2, jLabel3, jLabel4, jLabel5, jLabel6, jLabel7, nameTextField});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(dobField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(genderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(addressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(contactTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backJButton)
                    .addComponent(registerJButton))
                .addGap(26, 26, 26)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {addressTextField, contactTextField, emailTextField, jLabel2, jLabel3, jLabel4, jLabel5, jLabel6, jLabel7, nameTextField});

    }// </editor-fold>//GEN-END:initComponents

    private void registerJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerJButtonActionPerformed
        // TODO add your handling code here:
         
        try{
                if(nameTextField.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Name cannot be empty", "Warning", JOptionPane.WARNING_MESSAGE);
                }
 
//                else if(dobField.getDate()){
//                JOptionPane.showMessageDialog(null, "Date of Birth cannot be empty", "Warning", JOptionPane.WARNING_MESSAGE);
//                }
                
                else if(genderComboBox.getSelectedItem().equals("Select")){
                JOptionPane.showMessageDialog(null, "Choose a Gender", "Warning", JOptionPane.WARNING_MESSAGE);
                }
          
                else if(addressTextField.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Address cannot be empty", "Warning", JOptionPane.WARNING_MESSAGE);
                }
                
                else if(contactTextField.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Contact Number cannot be empty", "Warning", JOptionPane.WARNING_MESSAGE);
                }
                
                else if(emailTextField.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "E-mail cannot be empty", "Warning", JOptionPane.WARNING_MESSAGE);
                }
                
                else{
                
                    String name = nameTextField.getText();
                    String email = emailTextField.getText();
                    Date dob = dobField.getDate();

                    String cont = contactTextField.getText();
                    String add = addressTextField.getText();
                    String gender = genderComboBox.getSelectedItem().toString();

                    Patient p = new Patient();
                    p.setName(name);
                    p.setEmail(email);
                    p.setDateOfBirth(dob);
                    p.setContactNo(cont);
                    p.setAddress(add);
                    p.setGender(gender);
        
            //      PatientOrganisation po = new PatientOrganisation();
                    Patient p1 = org.getPatientDirectory().createPatient(p);
            //      System.out.println(p1);
        
                
                JOptionPane.showMessageDialog(null, "Patient Details added Successfully");
                
                    //reset fields
                    nameTextField.setText("");
                    emailTextField.setText("");
                    contactTextField.setText("");
                    addressTextField.setText("");
                    genderComboBox.setSelectedIndex(0);
                    
                    
                    }
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, "Invalid Data! Please enter valid data.", "Warning", JOptionPane.WARNING_MESSAGE);
            }
       
        
    }//GEN-LAST:event_registerJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        containerJPanel.remove(this);
        Component[] componentArray = containerJPanel.getComponents();
        Component component = componentArray[componentArray.length - 1];
        PatientWorkAreaPanel sysAdminwjp = (PatientWorkAreaPanel) component;
//        sysAdminwjp.populateTree();

        CardLayout layout = (CardLayout) containerJPanel.getLayout();
        layout.previous(containerJPanel);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void dobFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dobFieldActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_dobFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressTextField;
    private javax.swing.JButton backJButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JTextField contactTextField;
    private org.jdesktop.swingx.JXDatePicker dobField;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JComboBox genderComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JButton registerJButton;
    // End of variables declaration//GEN-END:variables
}
